apiVersion: v1
kind: Service
metadata:
  name: qn-service
  annotations:
    cloud.google.com/backend-config: '{"default": "qn-service-backendconfig"}'
  labels:
    app: qn-service
spec:
  selector:
    app: qn-service
  type: ClusterIP
  ports:
    - name: qn-service
      port: 3002
      targetPort: 3002