apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  labels:
    app: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: asia-southeast1-docker.pkg.dev/peerprep-440702/peerprep/user:latest
          ports:
            - name: user-service
              containerPort: 3001
          env:
          - name: ENV
            valueFrom:
              secretKeyRef:
                name: env
                key: ENV
          - name: DB_CLOUD_URI
            valueFrom:
              secretKeyRef:
                name: env
                key: DB_URI_USER
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: env
                key: JWT_SECRET
      restartPolicy: Always

      