apiVersion: v1
kind: Service
metadata:
  name: user-service
  annotations:
    cloud.google.com/backend-config: '{"default": "user-service-backendconfig"}'
  labels:
    app: user-service
spec:
  selector:
    app: user-service
  type: ClusterIP
  ports:
    - name: user-service
      port: 3001
      targetPort: 3001