apiVersion: v1
kind: Service
metadata:
  name: match-service
  annotations:
    cloud.google.com/backend-config: '{"default": "match-service-backendconfig"}'
  labels:
    app: match-service
spec:
  selector:
    app: match-service
  type: ClusterIP
  ports:
    - name: match-service
      port: 3003
      targetPort: 3003