apiVersion: apps/v1
kind: Deployment
metadata:
  name: match-service
  labels:
    app: match-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: match-service
  template:
    metadata:
      labels:
        app: match-service
    spec:
      containers:
        - name: match-service
          image: asia-southeast1-docker.pkg.dev/peerprep-440702/peerprep/matching:latest
          ports:
            - name: match-service
              containerPort: 3003
          env:
          - name: REDIS_URL
            valueFrom:
              secretKeyRef:
                name: env
                key: REDIS_URL
      restartPolicy: Always

      