apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-service
  labels:
    app: ai-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-service
  template:
    metadata:
      labels:
        app: ai-service
    spec:
      containers:
        - name: ai-service
          image: asia-southeast1-docker.pkg.dev/peerprep-440702/peerprep/ai:latest
          ports:
            - name: ai-service
              containerPort: 3005
          env:
          - name: ENV
            valueFrom:
              secretKeyRef:
                name: env
                key: ENV
          - name: GEMINI_API_KEY
            valueFrom:
              secretKeyRef:
                name: env
                key: GEMINI_API_KEY
      restartPolicy: Always

      