apiVersion: v1
kind: Service
metadata:
  name: ai-service
  annotations:
    cloud.google.com/backend-config: '{"default": "ai-service-backendconfig"}'
  labels:
    app: ai-service
spec:
  selector:
    app: ai-service
  type: ClusterIP
  ports:
    - name: ai-service
      port: 3005
      targetPort: 3005