services:
  user:
    build:
      context: ./user-service
      dockerfile: Dockerfile
      args:
        - PORT=${PORT_USER}
    ports:
      - ${PORT_USER}:${PORT_USER}
    environment:
      - ENV
      - DB_CLOUD_URI=${DB_URI_USER}
      - DB_LOCAL_URI=${DB_URI_USER}
      - JWT_SECRET

  questions:
    build:
      context: ./question-service
      dockerfile: Dockerfile
      args:
        - PORT=${PORT_QUESTION}
    ports:
      - ${PORT_QUESTION}:${PORT_QUESTION}
    environment:
      - ENV
      - DB_CLOUD_URI=${DB_URI_QUESTION}

  history-service:
    build:
      context: ./history-service  
      dockerfile: Dockerfile       
      args:
        - PORT=${PORT_HISTORY}
    ports:
      - ${PORT_HISTORY}:${PORT_HISTORY}
    environment:
      - ENV
      - DB_URI_HISTORY=${DB_URI_HISTORY}

    depends_on:
      - matching-redis
    networks:
      - matching

  matching-redis:
    image: redis
    networks:
      - matching
    expose:
      - 6379

  matching:
    build:
      context: ./matching-service
      dockerfile: Dockerfile
      args:
        - PORT=${PORT_MATCHING}
    ports:
      - ${PORT_MATCHING}:${PORT_MATCHING}
    depends_on:
      - matching-redis
    networks:
      - matching
    environment:
      - REDIS_URL=redis://matching-redis:6379

networks:
  matching:
    driver: bridge