name: Static Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install Client Dependencies
        run: |
            cd client
            npm ci
            cd ..
      - name: Install Server Dependencies
        run: |
            cd server
            npm ci
            cd ..
      - name: Install Outer Folder Dependencies
        run: |
            npm ci
      - name: Run Lint Checks (eslint)
        run: npx eslint .