name: Automated Testing (Client)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  client:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ./client
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_REACT_APP_API_BASE_URL: http://localhost
          directory: .
          file_name: .env
          fail_on_empty: false
          sort_keys: false
      - name: Install Client Dependencies
        run: npm ci
      - name: Run Tests
        run: npm run ci -- --coverage
      - name: Upload results to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
